import type { Metadata } from "next";
import { authOptions } from "@/lib/auth";
import { cn } from "@/lib/classnames";
import { getServerSession } from "next-auth";
import { Jost } from "next/font/google";
import "normalize.css";
import { prisma } from "@/lib/prisma";

const font = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getServerSession(authOptions);
  const test = await prisma.user.findMany();
  console.log(test);
  return (
    <html lang="en">
      <body className={cn(font.className)}>{children}</body>
    </html>
  );
}
